spring.application.name=AuthenticationService
server.port=8081

# PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/SOA-AUTH
spring.datasource.username=postgres
spring.datasource.password=1619
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# JWT
jwt.secret=VGhpc0lzQVN0cm9uZ0RlbW9TZWNyZXRLZXlGb3JKV1RTaW1wbGVtZW50aXRpb24xMjM0NTY3ODkw
jwt.expiration-ms=900000

# Eureka
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
eureka.instance.prefer-ip-address=true