spring.application.name=APIGATEWAY
server.port=8080

eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
eureka.client.registry-fetch-interval-seconds=3
eureka.instance.prefer-ip-address=true

spring.cloud.gateway.routes[0].id=AUTHENTICATIONSERVICE
spring.cloud.gateway.routes[0].uri=lb://AUTHENTICATIONSERVICE
spring.cloud.gateway.routes[0].predicates[0]=Path=/api/auth/**
spring.cloud.gateway.routes[0].filters[0]=CircuitBreaker=AUTH_SERVICE_CB,fallbackUri=forward:/fallback/auth

spring.cloud.gateway.routes[1].id=CONTENT-SERVICE
spring.cloud.gateway.routes[1].uri=lb://CONTENT-SERVICE
spring.cloud.gateway.routes[1].predicates[0]=Path=/content/**
spring.cloud.gateway.routes[1].filters[0]=CircuitBreaker=CONTENT_SERVICE_CB,fallbackUri=forward:/fallback/content

spring.cloud.gateway.routes[2].id=ACCESS-SERVICE
spring.cloud.gateway.routes[2].uri=lb://ACCESS-SERVICE
spring.cloud.gateway.routes[2].predicates[0]=Path=/access/**
spring.cloud.gateway.routes[2].filters[0]=CircuitBreaker=ACCESS_SERVICE_CB,fallbackUri=forward:/fallback/access

# Gateway Response Timeout
spring.cloud.gateway.httpclient.response-timeout=5s
spring.cloud.gateway.httpclient.connect-timeout=5000

# Resilience4j Time Limiter Timeout
resilience4j.timelimiter.configs.default.timeout-duration=5s

# Resilience4j Circuit Breaker Configuration
resilience4j.circuitbreaker.instances.AUTH_SERVICE_CB.sliding-window-type=COUNT_BASED
resilience4j.circuitbreaker.instances.AUTH_SERVICE_CB.sliding-window-size=10
resilience4j.circuitbreaker.instances.AUTH_SERVICE_CB.failure-rate-threshold=50
resilience4j.circuitbreaker.instances.AUTH_SERVICE_CB.wait-duration-in-open-state=10s
resilience4j.circuitbreaker.instances.AUTH_SERVICE_CB.permitted-number-of-calls-in-half-open-state=3
resilience4j.circuitbreaker.instances.AUTH_SERVICE_CB.minimum-number-of-calls=5

resilience4j.circuitbreaker.instances.CONTENT_SERVICE_CB.sliding-window-type=COUNT_BASED
resilience4j.circuitbreaker.instances.CONTENT_SERVICE_CB.sliding-window-size=10
resilience4j.circuitbreaker.instances.CONTENT_SERVICE_CB.failure-rate-threshold=50
resilience4j.circuitbreaker.instances.CONTENT_SERVICE_CB.wait-duration-in-open-state=10s
resilience4j.circuitbreaker.instances.CONTENT_SERVICE_CB.permitted-number-of-calls-in-half-open-state=3
resilience4j.circuitbreaker.instances.CONTENT_SERVICE_CB.minimum-number-of-calls=5

resilience4j.circuitbreaker.instances.ACCESS_SERVICE_CB.sliding-window-type=COUNT_BASED
resilience4j.circuitbreaker.instances.ACCESS_SERVICE_CB.sliding-window-size=10
resilience4j.circuitbreaker.instances.ACCESS_SERVICE_CB.failure-rate-threshold=50
resilience4j.circuitbreaker.instances.ACCESS_SERVICE_CB.wait-duration-in-open-state=10s
resilience4j.circuitbreaker.instances.ACCESS_SERVICE_CB.permitted-number-of-calls-in-half-open-state=3
resilience4j.circuitbreaker.instances.ACCESS_SERVICE_CB.minimum-number-of-calls=5