spring.application.name=APIGATEWAY
server.port=8080

eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
eureka.client.registry-fetch-interval-seconds=3
eureka.instance.prefer-ip-address=true

spring.cloud.gateway.routes[0].id=authentication-service
spring.cloud.gateway.routes[0].uri=lb://AUTHENTICATIONSERVICE
spring.cloud.gateway.routes[0].predicates[0]=Path=/api/auth/**

spring.cloud.gateway.routes[1].id=CONTENT-SERVICE
spring.cloud.gateway.routes[1].uri=lb://CONTENT-SERVICE
spring.cloud.gateway.routes[1].predicates[0]=Path=/content/**


spring.cloud.gateway.routes[2].id=ACCESS-SERVICE
spring.cloud.gateway.routes[2].uri=lb://CONTENT-SERVICE
spring.cloud.gateway.routes[2].predicates[0]=Path=/access/**