spring.application.name=ACCESS-SERVICE

server.port=8083

spring.datasource.url=jdbc:postgresql://localhost:5432/SOA-ACCESS
spring.datasource.username=postgres
spring.datasource.password=1619

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

eureka.client.service-url.defaultZone=http://localhost:8761/eureka

# JWT
jwt.secret=MlOIoVPDIcBLSCaymOKFcZKC7xtorTc/NhNVHs9llFI=